
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mahesh
 */
public class BIll_Details extends javax.swing.JFrame {
       PreparedStatement pst=null;
        ResultSet rs=null;
        Connection con=null;
        static String id;
    /**
     * Creates new form BIll_Details
     */
    public BIll_Details() {
        initComponents();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");

            con = DriverManager.getConnection("jdbc:mysql://localhost:3309/hotelmsr", "root", "");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Registration_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
        showdataintable();
    }
    
      public void showdataintable() {
    try {
        
        pst = con.prepareStatement("SELECT Bill_Id, room_no, Username, Mobile_no, Email, id_proof_type, id_no, in_date, Price FROM customer_details WHERE status = ?");
        pst.setString(1, "Check Out");
        rs = pst.executeQuery();
        ResultSetMetaData rsmd = rs.getMetaData();
        int n = rsmd.getColumnCount();
        DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
        df.setRowCount(0);

        while (rs.next()) {
            Vector<Object> v = new Vector<>();
            for (int i = 1; i <= n; i++) {
                v.add(rs.getObject(i)); 
            }

            
            String roomNo = rs.getString("room_no");

           
            PreparedStatement pst2 = con.prepareStatement("SELECT out_date, total_days, total_price FROM check_out_details WHERE room_no = ?");
            pst2.setString(1, roomNo);
            ResultSet rs2 = pst2.executeQuery();

            if (rs2.next()) {
                v.add(rs2.getString("out_date"));
                v.add(rs2.getString("total_days"));
                v.add(rs2.getString("total_price"));
            } else {
                
                v.add("");
                v.add("");
                v.add("");
            }

            
            df.addRow(v);

            
            rs2.close();
            pst2.close();
        }

       
        rs.close();
        pst.close();
    } catch (SQLException ex) {
        Logger.getLogger(CustomerCheckOut.class.getName()).log(Level.SEVERE, null, ex);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtoutdate = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(999, 0, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Bill ID", "Room Number", "Customer Name ", "Mobile Number", "Email ID", "ID Proof Type", "ID Proof Number", "Check IN Date", "Price", "Check Out Date", "Days Of Stay", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 354, 1010, 308));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill.png"))); // NOI18N
        jLabel1.setText("Customer Bill Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 313, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setText("Search By Check - Out Date ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 207, 246, -1));

        txtoutdate.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtoutdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoutdateActionPerformed(evt);
            }
        });
        getContentPane().add(txtoutdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 201, 154, 38));

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 200, -1, 39));

        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 200, -1, 39));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Double Click On Row To Open Bill ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 103, 385, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkinbg.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

          
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtoutdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoutdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoutdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
             try {
        
        pst = con.prepareStatement("SELECT Bill_Id, room_no, Username, Mobile_no, Email, id_proof_type, id_no, in_date, Price FROM customer_details WHERE status = ?");
        pst.setString(1, "Check Out");
        rs = pst.executeQuery();
        ResultSetMetaData rsmd = rs.getMetaData();
        int n = rsmd.getColumnCount();
        DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
        df.setRowCount(0);

        while (rs.next()) {
            Vector<Object> v = new Vector<>();
            for (int i = 1; i <= n; i++) {
                v.add(rs.getObject(i)); 
            }

            
            String roomNo = rs.getString("room_no");
          
            String outDate = txtoutdate.getText();

           
            PreparedStatement pst2 = con.prepareStatement("SELECT out_date, total_days, total_price FROM check_out_details WHERE room_no = ? AND out_date = ?");
            pst2.setString(1, roomNo);
            pst2.setString(2, outDate);
            ResultSet rs2 = pst2.executeQuery();

            if (rs2.next()) {
                v.add(rs2.getString("out_date"));
                v.add(rs2.getString("total_days"));
                v.add(rs2.getString("total_price"));
            } else {
                
                v.add("");
                v.add("");
                v.add("");
            }

           
            df.addRow(v);

            
            rs2.close();
            pst2.close();
        }

        
        rs.close();
        pst.close();
    } catch (SQLException ex) {
        Logger.getLogger(CustomerCheckOut.class.getName()).log(Level.SEVERE, null, ex);
    }


      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  showdataintable();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      
    jTable1.addMouseListener(new MouseAdapter() {
    public void mouseClicked(MouseEvent evt) {
        if (evt.getClickCount() == 2) {
            DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
            int selectedRowIndex = jTable1.getSelectedRow();
            if (selectedRowIndex != -1) { // Ensure a row is selected
                Object value = df.getValueAt(selectedRowIndex, 0);
                String id = value.toString(); // Convert the value to a String
                // Use the constructor that accepts an ID
                new Bill_Print(id).setVisible(true);
            }
        }
    }
});



        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BIll_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BIll_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BIll_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BIll_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BIll_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtoutdate;
    // End of variables declaration//GEN-END:variables
}
