
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mahesh
 */
public class CustomerCheckIn extends javax.swing.JFrame {
        PreparedStatement pst=null;
        ResultSet rs=null;
        Connection con=null;
    /**
     * Creates new form CustomerCheckIn
     */
    public CustomerCheckIn() {
        initComponents();
        SimpleDateFormat obj=new SimpleDateFormat("yyyy-MM-dd");
        Date date=new Date();
        indate.setText(obj.format(date));
        
         try {
            Class.forName("com.mysql.jdbc.Driver");

            con = DriverManager.getConnection("jdbc:mysql://localhost:3309/hotelmsr", "root", "");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Registration_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
       rooms();
    }
    
        public void rooms(){
            try {
                pst=con.prepareStatement("Select roomno from room_details where Bed_type=? and Room_type=? and status=? ");
               pst.setString(1, bedcombo.getItemAt(bedcombo.getSelectedIndex()));
                pst.setString(2, roomtypecombo.getItemAt(roomtypecombo.getSelectedIndex()));
                 pst.setString(3, statuscombo.getItemAt(statuscombo.getSelectedIndex()));
                 rs=pst.executeQuery();
                 roomnocombo.removeAllItems();
                 while(rs.next()){
                     roomnocombo.addItem(rs.getString("roomno"));
                 }
                 pst=con.prepareStatement("select Price from room_details where roomno=?");
                 pst.setString(1, roomnocombo.getItemAt(roomnocombo.getSelectedIndex()));
                 rs=pst.executeQuery();
                 if(rs.next()){
                     price.setText(rs.getString("Price"));
                 }
            } catch (SQLException ex) {
                Logger.getLogger(CustomerCheckIn.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        mono = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        gendercombo = new javax.swing.JComboBox<>();
        nationality = new javax.swing.JTextField();
        Idcombo = new javax.swing.JComboBox<>();
        idno = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        indate = new javax.swing.JTextField();
        checkinbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        roomnocombo = new javax.swing.JComboBox<>();
        bedcombo = new javax.swing.JComboBox<>();
        roomtypecombo = new javax.swing.JComboBox<>();
        statuscombo = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check-in-desk.png"))); // NOI18N
        jLabel1.setText("Customer Check-in");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Name Of Customer");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 117, 210, 32));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Mobile Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 196, 160, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Email Id");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 344, 130, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Gender");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 416, 100, 28));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 270, 100, 28));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Check-In Date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 569, 140, 27));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Nationality");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 497, 110, 27));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("ID Proof Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 649, 170, 32));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Room Number");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 195, 150, 32));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("ID Proof Type");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 562, 160, 40));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Room Type");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 274, 120, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Bed Type");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 344, 110, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Price Of Room");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 493, 180, 35));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Availability Status");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 415, 200, 30));

        name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 155, 227, -1));

        mono.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(mono, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 230, 227, 28));

        add.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 304, 227, -1));

        email.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 381, 227, -1));

        gendercombo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gendercombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        getContentPane().add(gendercombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 451, 227, -1));

        nationality.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalityActionPerformed(evt);
            }
        });
        getContentPane().add(nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 534, 227, -1));

        Idcombo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Idcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aadhar Card", "Pan Card", "Voter ID Card ", "Driving Licence", "Passport", " " }));
        getContentPane().add(Idcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 608, 227, -1));

        idno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(idno, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 693, 227, -1));

        age.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 155, 227, -1));

        price.setEditable(false);
        price.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 534, 227, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Age");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 129, 60, -1));

        indate.setEditable(false);
        indate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        indate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indateActionPerformed(evt);
            }
        });
        getContentPane().add(indate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 608, 227, -1));

        checkinbtn.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        checkinbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        checkinbtn.setText("Check-In Now");
        checkinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinbtnActionPerformed(evt);
            }
        });
        getContentPane().add(checkinbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 713, 174, -1));

        clearbtn.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        clearbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tool.png"))); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 713, 116, -1));

        roomnocombo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(roomnocombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 230, -1));

        bedcombo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bedcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single Bed", "Double Bed ", "Multi Beds", " " }));
        bedcombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bedcomboItemStateChanged(evt);
            }
        });
        getContentPane().add(bedcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 230, -1));

        roomtypecombo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        roomtypecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A/C Room", "Non A/C Room", "Deluxe A/C Room", "Deluxe Non A/C Room", "Super Deluxe Room", "Couple Sweet Room", "Nature Sight Room ", " " }));
        roomtypecombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                roomtypecomboItemStateChanged(evt);
            }
        });
        getContentPane().add(roomtypecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 230, -1));

        statuscombo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        statuscombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Not Available", " " }));
        getContentPane().add(statuscombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 230, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/htnm.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 340, 220));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkinbg.jpg"))); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void nationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationalityActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void indateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indateActionPerformed

    private void checkinbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinbtnActionPerformed
       if(  name.getText().equals("")) {
           JOptionPane.showMessageDialog(this, " All Feilds Should Be Filled");
           name.requestFocus();
            } else if(mono.getText().equals("")){
                JOptionPane.showMessageDialog(this, " All Feilds Should Be Filled");
                mono.requestFocus();
            }
            else if(email.getText().equals(" ")){
                JOptionPane.showMessageDialog(this, " All Feilds Should Be Filled");
                email.requestFocus();
            }
            else if(add.getText().equals(" ")){
                JOptionPane.showMessageDialog(this, " All Feilds Should Be Filled");
                add.requestFocus();
            }
            else if(idno.getText().equals(" ")){
                JOptionPane.showMessageDialog(this, " All Feilds Should Be Filled");
                idno.requestFocus();
            }
            else  if(nationality.getText().equals(" ")){
                JOptionPane.showMessageDialog(this, " All Feilds Should Be Filled");
                nationality.requestFocus();
            }
            
            else  if(age.getText().equals(" ")){
                JOptionPane.showMessageDialog(this, " All Feilds Should Be Filled");
                age.requestFocus();
            }
            else{
                try {
                    pst=con.prepareStatement("insert into customer_details (Username,Mobile_no,Email,address,gender,in_date,id_proof_type,id_no,nationality,Bed_type,room_type,Price,status,room_no,age)values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                    pst.setString(1, name.getText());
                    pst.setString(2, mono.getText());
                    pst.setString(3, email.getText());
                    pst.setString(4, add.getText());
                    pst.setString(5, gendercombo.getItemAt(gendercombo.getSelectedIndex()));
                    pst.setString(6, indate.getText());
                    pst.setString(7, Idcombo.getItemAt(Idcombo.getSelectedIndex()));
                    pst.setString(8, idno.getText());
                    pst.setString(9, nationality.getText());
                    pst.setString(10, bedcombo.getItemAt(bedcombo.getSelectedIndex()));
                    pst.setString(11, roomtypecombo.getItemAt(roomtypecombo.getSelectedIndex()));
                    pst.setString(12, price.getText());
                    pst.setString(13, statuscombo.getItemAt(statuscombo.getSelectedIndex()));
                    pst.setString(14, roomnocombo.getItemAt(roomnocombo.getSelectedIndex()));
                    pst.setString(15, age.getText());
                    
                    pst.executeUpdate();
                    
                    JOptionPane.showMessageDialog(this, " Customer Check-In Successfully");
                    name.setText(" ");
                    mono.setText(" ");
                    add.setText(" ");
                    email.setText(" ");
                    nationality.setText(" ");
                    idno.setText(" ");
                    age.setText(" ");
                    pst=con.prepareStatement("Update room_details set status=? where roomno=?");
                    pst.setString(1, "Not Available");
                    pst.setString(2, roomnocombo.getItemAt(roomnocombo.getSelectedIndex()));
                    pst.executeUpdate();
                    rooms();
                    
                } catch (SQLException ex) {
                    Logger.getLogger(CustomerCheckIn.class.getName()).log(Level.SEVERE, null, ex);
                }
            }



        // TODO add your handling code here:
    }//GEN-LAST:event_checkinbtnActionPerformed

    private void roomtypecomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_roomtypecomboItemStateChanged
     rooms();     // TODO add your handling code here:
    }//GEN-LAST:event_roomtypecomboItemStateChanged

    private void bedcomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bedcomboItemStateChanged
    rooms();        // TODO add your handling code here:
    }//GEN-LAST:event_bedcomboItemStateChanged

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
       name.setText(" ");
       mono.setText(" ");
       add.setText(" ");
        email.setText(" ");
        nationality.setText(" ");
        idno.setText(" ");
        age.setText(" ");// TODO add your handling code here:
    }//GEN-LAST:event_clearbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Idcombo;
    private javax.swing.JTextField add;
    private javax.swing.JTextField age;
    private javax.swing.JComboBox<String> bedcombo;
    private javax.swing.JButton checkinbtn;
    private javax.swing.JButton clearbtn;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> gendercombo;
    private javax.swing.JTextField idno;
    private javax.swing.JTextField indate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mono;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nationality;
    private javax.swing.JTextField price;
    private javax.swing.JComboBox<String> roomnocombo;
    private javax.swing.JComboBox<String> roomtypecombo;
    private javax.swing.JComboBox<String> statuscombo;
    // End of variables declaration//GEN-END:variables
}
