
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mahesh
 */
public class Manage_Rooms extends javax.swing.JFrame {
        PreparedStatement pst=null;
        ResultSet rs=null;
        Connection con=null;
        
    /**
     * Creates new form Manage_Rooms
     */
    public Manage_Rooms() {
        initComponents();
         try {
            Class.forName("com.mysql.jdbc.Driver");

            con = DriverManager.getConnection("jdbc:mysql://localhost:3309/hotelmsr", "root", "");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Registration_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        SHowRecordintable();
    }
    
    public  void SHowRecordintable(){
        int c=0;
            try {
                pst=con.prepareStatement("select * from room_details");
                rs=pst.executeQuery();
                ResultSetMetaData rsmd=rs.getMetaData();
                c=rsmd.getColumnCount();
                DefaultTableModel DModel=(DefaultTableModel) jTable2.getModel();
                DModel.setRowCount(0);
                while (rs.next()) {
                    Vector column = new Vector();
                    for(int i=1;i<=c;i++){
                        column.add(rs.getString("roomno"));
                        column.add(rs.getString("Room_type"));
                        column.add(rs.getString("Bed_type"));
                        column.add(rs.getString("Price"));
                        column.add(rs.getString("status"));
                    }
                    DModel.addRow(column);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Manage_Rooms.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        roomno = new javax.swing.JTextField();
        typecombo = new javax.swing.JComboBox<>();
        price = new javax.swing.JTextField();
        statuscombo = new javax.swing.JComboBox<>();
        bedcombo = new javax.swing.JComboBox<>();
        confobtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room No", "Room Type", "Bed Type", "Price", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 990, 350));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/roommanage.png"))); // NOI18N
        jLabel1.setText("Manage Rooms");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 344, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 124, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Room Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 611, 110, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Bed Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 100, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Price ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 494, 49, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Status");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 611, 100, -1));

        roomno.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        roomno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnoActionPerformed(evt);
            }
        });
        getContentPane().add(roomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 542, 134, -1));

        typecombo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        typecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A/C Room", "Non A/C Room", "Deluxe A/C Room", "Deluxe Non A/C Room", "Super Deluxe Room", "Couple Sweet Room", "Nature Sight Room ", "Honeymoon Sweet Room", " " }));
        typecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typecomboActionPerformed(evt);
            }
        });
        getContentPane().add(typecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 652, 129, -1));

        price.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 542, 132, -1));

        statuscombo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        statuscombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available ", "Not Available ", " " }));
        statuscombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statuscomboActionPerformed(evt);
            }
        });
        getContentPane().add(statuscombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 652, -1, -1));

        bedcombo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        bedcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single Bed", "Double Bed ", "Multi Beds", " " }));
        bedcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedcomboActionPerformed(evt);
            }
        });
        getContentPane().add(bedcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 567, -1, -1));

        confobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verify users.png"))); // NOI18N
        confobtn.setText("Update Room ");
        confobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confobtnActionPerformed(evt);
            }
        });
        getContentPane().add(confobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 650, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manageroombg.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 1050, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomnoActionPerformed

    private void typecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typecomboActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void statuscomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statuscomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statuscomboActionPerformed

    private void confobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confobtnActionPerformed
      if(roomno.getText().equals(" ")){
          JOptionPane.showMessageDialog(this, " All Feilds Should Be Filled");
          roomno.requestFocus();
      }// TODO add your handling code here:
      else if(price.getText().equals(" ")){
          JOptionPane.showMessageDialog(this, " All Feilds Should Be Filled");
          price.requestFocus();
      }
      else{
          try {
              pst=con.prepareStatement("select * from room_details where roomno=?");
              pst.setString(1, roomno.getText());
              rs=pst.executeQuery();
              if(rs.next()){
               JOptionPane.showMessageDialog(this, " Room No Already Exist");  
              }
              else{
                  pst=con.prepareStatement("insert into room_details(roomno,Room_type,Bed_type,Price,status)values(?,?,?,?,?)");
                   pst.setString(1, roomno.getText());
                    pst.setString(2, typecombo.getItemAt(typecombo.getSelectedIndex()));
                     pst.setString(3, bedcombo.getItemAt(bedcombo.getSelectedIndex()));
                      pst.setString(4, price.getText());
                     pst.setString(5, statuscombo.getItemAt(statuscombo.getSelectedIndex()));
                     pst.executeUpdate();
                      JOptionPane.showMessageDialog(this, " Room Added Successfully");  
                      SHowRecordintable();
                      roomno.setText("");
                      price.setText("");
              }
          } catch (SQLException ex) {
              Logger.getLogger(Manage_Rooms.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
    }//GEN-LAST:event_confobtnActionPerformed

    private void bedcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bedcomboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Rooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bedcombo;
    private javax.swing.JButton confobtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField price;
    private javax.swing.JTextField roomno;
    private javax.swing.JComboBox<String> statuscombo;
    private javax.swing.JComboBox<String> typecombo;
    // End of variables declaration//GEN-END:variables
}
